import React, { useMemo, useState } from "react";
import { createAssessment, provisionAccount, saveAssignment, syncSourceTemplates } from "../residentApi";

const today = () => new Date().toISOString().slice(0, 10);
const readableDate = (value) => new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`));
const roleLabel = { admin: "Admin", evaluator: "Evaluator", resident: "Resident" };

function History({ assessments, user, profiles }) {
  const names = new Map(profiles.map((profile) => [profile.id, profile.name]));
  if (!assessments.length) return <section className="resident-panel empty"><h2>ยังไม่มีผลการประเมิน</h2><p>{user.role === "resident" ? "ผล EPA/PBA ที่อาจารย์ลงนามแล้วจะแสดงที่นี่" : "เลือก Resident และแบบประเมินเพื่อเริ่มบันทึก"}</p></section>;
  return <section className="resident-panel"><h2>ประวัติการประเมิน</h2><div className="resident-table-wrap"><table><thead><tr><th>วันที่</th><th>Resident</th><th>แบบประเมิน</th><th>ผู้ประเมิน</th><th>ผลสรุป</th></tr></thead><tbody>{assessments.map((item) => <tr key={item.id}><td>{readableDate(item.assessment_date)}</td><td>{names.get(item.resident_id) || "—"}</td><td>{item.resident_template_definitions?.template_code} · {item.resident_template_definitions?.title}</td><td>{names.get(item.evaluator_id) || "—"}</td><td>{item.overall_outcome || "—"}</td></tr>)}</tbody></table></div></section>;
}

function EvaluationForm({ templates, residents, onSaved }) {
  const [templateId, setTemplateId] = useState(templates[0]?.id || ""); const [residentId, setResidentId] = useState(residents[0]?.id || ""); const [date, setDate] = useState(today()); const [context, setContext] = useState(""); const [activity, setActivity] = useState(""); const [outcome, setOutcome] = useState(""); const [comment, setComment] = useState(""); const [scores, setScores] = useState({}); const [comments, setComments] = useState({}); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const template = templates.find((item) => item.id === templateId);
  async function submit(event) { event.preventDefault(); if (!template || !residentId) return setError("กรุณาเลือก Resident และแบบประเมิน"); if (template.criteria.some((criterion) => !scores[criterion.id])) return setError("กรุณาให้คะแนนทุกข้อก่อนลงนาม"); setBusy(true); setError(""); try { await createAssessment({ templateId, residentId, date, context, activity, outcome, comment, scores: template.criteria.map((criterion) => ({ criterionId: criterion.id, score: scores[criterion.id], comment: comments[criterion.id] || "" })) }); await onSaved(); setScores({}); setComments({}); setContext(""); setActivity(""); setOutcome(""); setComment(""); } catch (nextError) { setError(nextError.message || "บันทึกผลประเมินไม่สำเร็จ"); } finally { setBusy(false); } }
  if (!templates.length) return <section className="resident-panel empty"><h2>ยังไม่มี catalog</h2><p>Admin ต้องกดซิงก์ EPA/PBA source ก่อนเริ่มประเมิน</p></section>;
  return <form className="resident-panel assessment-form" onSubmit={submit}><div className="section-heading"><div><h2>บันทึกการประเมิน</h2><p>คะแนนทุกข้อจำเป็นก่อนลงนาม และห้ามใส่ชื่อหรือ HN ผู้ป่วย</p></div></div><div className="resident-form-grid"><label>Resident<select value={residentId} onChange={(event) => setResidentId(event.target.value)} required><option value="">เลือก Resident</option>{residents.map((resident) => <option key={resident.id} value={resident.id}>{resident.name} · PGY {resident.pgy}</option>)}</select></label><label>วันที่ประเมิน<input type="date" value={date} max={today()} onChange={(event) => setDate(event.target.value)} required /></label><label>แบบประเมิน<select value={templateId} onChange={(event) => { setTemplateId(event.target.value); setScores({}); setComments({}); }}><option value="">เลือกแบบประเมิน</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.template_code} · {item.title}</option>)}</select></label><label>กิจกรรม/หัตถการ<input value={activity} onChange={(event) => setActivity(event.target.value)} maxLength="240" placeholder="เช่น Laparoscopic cholecystectomy" /></label><label className="wide">บริบททางคลินิกแบบไม่ระบุตัวตน<textarea value={context} onChange={(event) => setContext(event.target.value)} maxLength="500" rows="2" placeholder="ห้ามระบุชื่อผู้ป่วยหรือ HN" /></label></div>{template && <div className="criterion-list"><div className="criterion-head"><span>เกณฑ์จาก {template.source_file}</span>{template.score_options.map((score) => <b key={score}>{score}</b>)}<span>ข้อเสนอแนะ</span></div>{template.criteria.map((criterion) => <div className="criterion-row" key={criterion.id}><div><small>{criterion.criterion_code}</small><p>{criterion.criterion_text}</p></div>{template.score_options.map((score) => <label className="score-radio" key={score}><input type="radio" name={criterion.id} value={score} checked={scores[criterion.id] === score} onChange={() => setScores({ ...scores, [criterion.id]: score })} /><span>{score}</span></label>)}<input aria-label={`ข้อเสนอแนะ ${criterion.criterion_code}`} value={comments[criterion.id] || ""} onChange={(event) => setComments({ ...comments, [criterion.id]: event.target.value })} maxLength="1000" placeholder="ถ้ามี" /></div>)}</div>}<div className="resident-form-grid footer-fields"><label>ผลสรุป/Overall outcome<input value={outcome} onChange={(event) => setOutcome(event.target.value)} maxLength="80" placeholder="เช่น ผ่านการประเมิน" /></label><label className="wide">ความเห็นสรุป<textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength="2000" rows="3" /></label></div>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? "กำลังลงนาม…" : "ลงนามและบันทึกผลประเมิน"}</button></form>;
}

function Admin({ workspace, onRefresh }) {
  const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [account, setAccount] = useState({ fullName: "", email: "", role: "resident", pgy: "1" }); const [assignment, setAssignment] = useState({ evaluatorId: "", residentId: "" });
  const residents = workspace.profiles.filter((profile) => profile.pgy); const evaluators = workspace.profiles.filter((profile) => !profile.pgy && profile.id !== workspace.user.id);
  async function sync() { setSyncing(true); setError(""); try { await syncSourceTemplates(); await onRefresh(); setMessage("ซิงก์ EPA/PBA source สำเร็จ"); } catch (nextError) { setError(nextError.message); } finally { setSyncing(false); } }
  async function addAccount(event) { event.preventDefault(); setError(""); try { const result = await provisionAccount({ ...account, pgy: Number(account.pgy) }); setMessage(result.invitationSent ? "ส่งคำเชิญเปิดบัญชีแล้ว" : "อัปเดตสิทธิ์บัญชีแล้ว"); setAccount({ fullName: "", email: "", role: "resident", pgy: "1" }); await onRefresh(); } catch (nextError) { setError(nextError.message); } }
  async function assign(event) { event.preventDefault(); setError(""); try { await saveAssignment(assignment.evaluatorId, assignment.residentId); setMessage("บันทึกการมอบหมายผู้ประเมินแล้ว"); await onRefresh(); } catch (nextError) { setError(nextError.message); } }
  return <><section className="resident-panel admin-summary"><div><h2>Catalog EPA/PBA</h2><p>{workspace.templates.length} แบบประเมิน · สร้างจากไฟล์ใน EPA/ และ PBA/ เท่านั้น</p></div><button className="primary-button" onClick={sync} disabled={syncing}>{syncing ? "กำลังซิงก์…" : "ซิงก์ source catalog"}</button></section><div className="admin-grid"><form className="resident-panel" onSubmit={addAccount}><h2>เพิ่มบัญชี</h2><label>ชื่อ–นามสกุล<input value={account.fullName} onChange={(event) => setAccount({ ...account, fullName: event.target.value })} required /></label><label>อีเมล<input type="email" value={account.email} onChange={(event) => setAccount({ ...account, email: event.target.value })} required /></label><label>บทบาท<select value={account.role} onChange={(event) => setAccount({ ...account, role: event.target.value })}><option value="resident">Resident</option><option value="evaluator">Evaluator</option><option value="admin">Admin</option></select></label>{account.role === "resident" && <label>PGY<select value={account.pgy} onChange={(event) => setAccount({ ...account, pgy: event.target.value })}>{[1,2,3,4].map((year) => <option key={year} value={year}>PGY {year}</option>)}</select></label>}<button className="primary-button">ส่งคำเชิญ</button></form><form className="resident-panel" onSubmit={assign}><h2>มอบหมายผู้ประเมิน</h2><label>Evaluator<select value={assignment.evaluatorId} onChange={(event) => setAssignment({ ...assignment, evaluatorId: event.target.value })} required><option value="">เลือก Evaluator</option>{evaluators.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Resident<select value={assignment.residentId} onChange={(event) => setAssignment({ ...assignment, residentId: event.target.value })} required><option value="">เลือก Resident</option>{residents.map((person) => <option key={person.id} value={person.id}>{person.name} · PGY {person.pgy}</option>)}</select></label><button className="primary-button">บันทึกการมอบหมาย</button></form></div>{(message || error) && <p className={error ? "form-error" : "form-success"}>{error || message}</p>}<section className="resident-panel"><h2>สถานะบัญชี</h2><div className="resident-table-wrap"><table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บทบาท/PGY</th></tr></thead><tbody>{workspace.profiles.map((person) => <tr key={person.id}><td>{person.name}</td><td>{person.email}</td><td>{person.pgy ? `Resident · PGY ${person.pgy}` : "Evaluator / Admin"}</td></tr>)}</tbody></table></div></section></>;
}

export default function ResidentPlatform({ workspace, onRefresh, onLogout }) {
  const [tab, setTab] = useState(workspace.user.role === "resident" ? "history" : workspace.user.role === "admin" ? "admin" : "assess"); const canEvaluate = workspace.user.role === "evaluator" || workspace.user.role === "admin";
  const residents = useMemo(() => workspace.user.role === "admin" ? workspace.profiles.filter((profile) => profile.pgy) : workspace.profiles.filter((profile) => workspace.assignments.some((assignment) => assignment.evaluator_id === workspace.user.id && assignment.resident_id === profile.id)), [workspace]);
  const nav = [["history", "ผลการประเมิน"]]; if (canEvaluate) nav.push(["assess", "ประเมิน EPA/PBA"]); if (workspace.user.role === "admin") nav.push(["admin", "จัดการระบบ"]);
  return <div className="resident-app"><header><div className="resident-brand"><img src="/surgery-cmu-logo.png" alt="Surgery CMU" /><div><strong>Resident Surgery Assessment</strong><span>EPA · PBA · ภาควิชาศัลยศาสตร์ มหาวิทยาลัยเชียงใหม่</span></div></div><div><span className="role-chip">{roleLabel[workspace.user.role]}</span><button className="text-button" onClick={onLogout}>ออกจากระบบ</button></div></header><nav>{nav.map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav><main><div className="page-heading"><div><h1>{tab === "admin" ? "จัดการระบบ Resident" : tab === "assess" ? "แบบประเมิน EPA/PBA" : "ผลการประเมินของฉัน"}</h1><p>{workspace.user.name}{workspace.user.pgy ? ` · PGY ${workspace.user.pgy}` : ""}</p></div></div>{tab === "admin" ? <Admin workspace={workspace} onRefresh={onRefresh} /> : tab === "assess" ? <EvaluationForm templates={workspace.templates} residents={residents} onSaved={onRefresh} /> : <History assessments={workspace.assessments} user={workspace.user} profiles={workspace.profiles} />}</main><footer>ข้อมูลการประเมินใช้เพื่อการศึกษาและการพัฒนาวิชาชีพ ห้ามบันทึกข้อมูลระบุตัวผู้ป่วย</footer></div>;
}
