import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (relativePath) => readFile(new URL(relativePath, import.meta.url), "utf8");

test("Resident can select only active registered Staff accounts with matching directory identities", async () => {
  const sql = await read("../supabase/migrations/20260909121917_resident_assessment_requests_notifications.sql");
  assert.match(sql, /create or replace function public\.list_registered_resident_staff\(\)/);
  assert.match(sql, /directory\.active and role\.active and role\.role = 'staff' and profile\.active/);
  assert.match(sql, /Selected Staff must match an active registered Staff account/);
  assert.match(sql, /directory\.auth_user_id = p_staff_id/);
});

test("assessment request and completion timestamps are generated by the database", async () => {
  const sql = await read("../supabase/migrations/20260909121917_resident_assessment_requests_notifications.sql");
  assert.match(sql, /submitted_at timestamptz not null default now\(\)/);
  assert.match(sql, /assessed_at timestamptz/);
  assert.match(sql, /set status = 'completed', assessment_id = v_assessment_id, assessed_at = now\(\)/);
  assert.match(sql, /request_row\.staff_id <> \(select auth\.uid\(\)\)/);
});

test("EPA C1-C2 are informational, C3 is the activity field, and scoring begins at C4", async () => {
  const [component, sql] = await Promise.all([
    read("../src/features/ResidentPlatform.jsx"),
    read("../supabase/migrations/20260909121917_resident_assessment_requests_notifications.sql"),
  ]);
  assert.match(component, /C1–C2 เป็นข้อมูลประกอบ ไม่เลือกระดับ/);
  assert.match(component, /C3 · ชื่อกิจกรรม/);
  assert.match(component, /\["C1", "C2", "C3"\]\.includes\(criterion\.criterion_code\)/);
  assert.match(sql, /template_row\.template_type = 'EPA' and criterion\.criterion_code in \('C1', 'C2', 'C3'\)/);
});

test("level controls support both three and five options and expose a full clickable radio target", async () => {
  const [component, css] = await Promise.all([
    read("../src/features/ResidentPlatform.jsx"),
    read("../src/resident.css"),
  ]);
  assert.match(component, /"--score-count": template\.score_options\.length/);
  assert.match(css, /repeat\(var\(--score-count,5\),55px\)/);
  assert.match(css, /\.score-radio input \{ inset:0; width:100%; height:100%; cursor:pointer; \}/);
  assert.match(component, /setScores\(\(current\) => \(\{ \.\.\.current, \[criterion\.id\]: score \}\)\)/);
});

test("web notifications and one idempotent 24-hour email reminder are server-backed", async () => {
  const [sql, notifier] = await Promise.all([
    read("../supabase/migrations/20260909121917_resident_assessment_requests_notifications.sql"),
    read("../supabase/functions/resident-assessment-notifier/index.ts"),
  ]);
  assert.match(sql, /unique \(request_id, recipient_id, notification_type\)/);
  assert.match(sql, /unique \(request_id, delivery_type\)/);
  assert.match(sql, /'assessment_requested'/);
  assert.match(sql, /'assessment_completed'/);
  assert.match(notifier, /24 \* 60 \* 60 \* 1000/);
  assert.match(notifier, /deliveryType: "initial" \| "reminder"/);
  assert.doesNotMatch(notifier, /clinical_context/);
});
